"""add_geocoding_metadata_fields

Revision ID: 9e275309deea
Revises: 
Create Date: 2025-09-30 02:47:30.248231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e275309deea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('geocoding_confidence', sa.String(length=50), nullable=True))
    op.add_column('empresa', sa.Column('geocoding_warning', sa.Text(), nullable=True))
    op.add_column('empresa', sa.Column('requires_verification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    
    # Índice espacial para búsquedas geográficas
    op.create_index('idx_empresa_coordenadas', 'empresa', ['latitud', 'longitud'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_empresa_coordenadas', table_name='empresa')
    op.drop_column('empresa', 'requires_verification')
    op.drop_column('empresa', 'geocoding_warning')
    op.drop_column('empresa', 'geocoding_confidence')
    # ### end Alembic commands ###
